apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message-processor.fullname" . }}-secrets
type: Opaque
data:
  rabbitmq-username: {{ .Values.secretValues.rabbitmqUsername | b64enc }}
  rabbitmq-password: {{ .Values.secretValues.rabbitmqPassword | b64enc }}
  db-username: {{ .Values.secretValues.dbUsername | b64enc }}
  db-password: {{ .Values.secretValues.dbPassword | b64enc }}
