apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-consumer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/samidala/message-processor.git'
    targetRevision: main
    path: devops/helm/message-processor
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: message-consumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
